### ISSUE TITLE
Theme priority via react-css-themr

### ISSUE THREAD

**Issue by iamyardem** [react-toolbox/react-toolbox#1017]
Hello. I've tried to apply theme via react-css-themr. But I found that default theme's classes apply first, therefore default classes have more priority. To fix it I need either use !important or write more specific selectors. For example,  I wrote following styles for input highlight bar. 

```css
  .bar {
    &:after, &:before {
      background-color: #c2c2c2;
    }
```

But it works only if I wrap it in div to make it more specific.

```css
div {
  .bar {
    &:after, &:before {
      background-color: #c2c2c2;
    }
  }
}
```

Is there any way to control priority of classes for themr approach? Can post-css autoprefixer cause such behavior?
