### ISSUE TITLE
Add theme for overlay of dialog

### ISSUE THREAD

**Issue by vikshv** [react-toolbox/react-toolbox#1055]
Please add theme prop for overlay component in dialog component

**Comment by frolant** [comment]
Yes. It is very important. This theme is very much needed. Often there is a problem with settings for overlay in dialog component. Please add it..

**Comment by gsawasthi25** [comment]
Yes this is must have thing.

In the meanwhile has anyone found any workaround for the same ??

**Comment by javivelasco** [comment]
Added under the namespace `overlay`. If you want to style it just pass the properties of the theme namespaced to the `Dialog`. For example:

```css
.overlay {
  &.overlayOverlay {
    background-color: red;
  }
}
```
