### ISSUE TITLE
Fixed tab header

### ISSUE THREAD

**Issue by thmshmm** [react-toolbox/react-toolbox#1103]
Hi, is there a way to fix the header of the Tabs component? Thanks in advance

**Comment by raulmatei** [comment]
It depends on you use case, I've had something similar, a page with tabs on top and fixed and the content scrollable, I've done it this way:
```js
      <Tab {...tabPropsNothingUnusual}>
        <div className={tabsCustomStyles.scrollable}>
          {content}
        </div>
      </Tab>
```

And the CSS for `.scrollable` is:

```css
.scrollable {
  height: 100%;
  overflow: auto;
}
```

styles added to `Tabs` through theme prop:

```css
.tabs {
  height: 100%;
}

.tab {
  height: 100%;
  padding: 0;

  > div {
    height: 100%;
  }
}
```

Not very clever but it worked.
