### ISSUE TITLE
AppBar on the doc site is different than what is available with the component

### ISSUE THREAD

**Issue by jerfowler** [react-toolbox/react-toolbox#1144]
First off, wonderful library! Very well done and the doc site is awesome!

However, it appears you guys don't eat your own dog food with the Appbar navigation links. The ones used on the doc page look much nicer than what is provided with the component. 

Take a look:

![image](https://cloud.githubusercontent.com/assets/188159/21957544/079350d0-da5e-11e6-878f-fb2ed30e63a6.png)

Looks like you guys rolled something custom in order to make use of react-router Links. Plus, the white typeface looks better and that pink bottom border is classy!

https://github.com/react-toolbox/react-toolbox/blob/dev/docs/app/components/navigation/index.js

It's a little bit of a cheat. So, I think the doc's navbar should be the default "out-of-the-box" component or at least available as an optional component. Plus, it should support wrapping react-router Link components, which I have to imagine is a common requirement for a lot of people.

**Comment by javivelasco** [comment]
That's a bit unfair 😁 If the site is not using some components directly, it doesn't mean the reason is because it's not possible. The site was implemented with the first version and there were some issues with customization for example. Also most components were not so flexible.

We are fixing stuff step by step and now this can be done without too much trouble. The site will be redesigned soon by the way, but there are other priorities, you can [check the roadmap](https://github.com/react-toolbox/react-toolbox/blob/dev/ROADMAP.md). Now let me tell you how can you do it, in my case I've used the `/spec` site in the same react-toolbox project.

Basically what you can do is to import the `Tabs` and `Tab` component and use them without content. The only issue is that by default the Tabs have a different height from what you want and a bit different styles, but you can tweak it with a theme as explained in both the docs and [react-toolbox-themr](github.com/javivelasco/react-css-themr). It would be something like:

```jsx
import tabsTheme from './tabsTheme.css';

// ....

<AppBar title={`React Toolbox Spec ${VERSION}`} fixed flat>
  <ButtonToolbox
    accent
    className={style.github}
    icon='web'
    floating
  />
  <Tabs
    index={this.state.active}
    className={tabsTheme.appbarTabs}
    onChange={this.handleTabChange}
    theme={tabsTheme}
  >
    <Tab label='Playground' />
    <Tab label='Github' />
  </Tabs>
</AppBar>
```

And the theme would look like:

```css
.appbarTabs {
  &.tabs {
    border: 1px solid transparent;
    height: 64px;
    position: absolute;
    right: 80px;
    top: 0;
  }

  & .navigation {
    align-items: center;
    height: 64px;
  }

  & .label {
    color: white;
    text-transform: capitalize;

    &.barActive {
      color: white;
    }
  }

  & .pointer {
    background-color: rgb(255, 64, 129);
    height: 4px;
    margin-top: 0;
    transform: translateY(-5px);
  }
}
```

And here is the result:

![kapture 2017-01-19 at 21 57 37](https://cloud.githubusercontent.com/assets/1634922/22125018/5b717456-de92-11e6-93f6-f4527df3ef19.gif)
