### ISSUE TITLE
unstyled div wrapping Panel

### ISSUE THREAD

**Issue by mjmdavis** [react-toolbox/react-toolbox#1304]
There is a style applied [here](https://github.com/react-toolbox/react-toolbox/blob/2.0.0-beta.6/components/layout/Layout.js#L106) to a div which wraps Panel.

I'm using create-react-app and react-toolbox-themr and this div is unstyled. I assume it should be somehow styled though as the lack of style breaks the flexbox that I expected to be in the Panel.

Is there some way to remedy this?

**Comment by mjmdavis** [comment]
I removed the unstyled div and added the following style to my panel to get it to behave as I wanted.

I feel as though I might be missing something though...

```css
.Main-panel {
    display: flex;
    flex-direction: column;
    bottom: 0;
}
```
