### ISSUE TITLE
Colors aren't RGB values

### ISSUE THREAD

**Issue by EnzoMartin** [react-toolbox/react-toolbox#131]
The way that [colors](/react-toolbox/react-toolbox/blob/master/components/_colors.scss) are currently set, you have to use `unquote`:

```scss
$red-faded: rgba($palette-red-50,0.5);
```

Results in:

```
 Argument `$color` of `rgba($color, $alpha)` must be a color
```

Although it's quite ugly, this works:

```scss
$red: unquote("rgb(#{$palette-red-50})");
$red-faded: rgba($red,0.5);

// OR

$red-faded: unquote("rgba(#{$palette-red-50},0.5)");
```

In the [globals](/react-toolbox/react-toolbox/blob/master/components/_globals.scss), invoking unquote is done throughout the file to get around this. Seems to be a fairly unnecessary convolution as the colors aren't used in any other way from the `colors.scss` file.

I propose changing the `colors.scss` to using the RGB values directly like so:

```scss
// Red
$palette-red-50: rgb(255,235,238);
$palette-red-100: rgb(255,205,210);
$palette-red-200: rgb(239,154,154);
$palette-red-300: rgb(229,115,115);
[...]
```

Which will eliminate the need to use `unquote`, and isn't a breaking change as `unquote` won't break if called on values that have no quotes.
