### ISSUE TITLE
Sidebar not a flexbox

### ISSUE THREAD

**Issue by mjmdavis** [react-toolbox/react-toolbox#1316]
The classnames combined [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/layout/Sidebar.js#L17) do not evaluate as expected.

The display style on the sidebar is evaluated to `display: block` despite setting classname to `Sidebar` and having the following class in css.

```css
.Sidebar {
    display: flex;
    flex-direction: column;
    bottom: 0;
}
```

Increasing the specificity as below fixes the issue for me. I'm not sure why this is happening. It seems like the `display` value is coming from [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/drawer/theme.css#L15).
```css
aside.Sidebar {
    display: flex;
    flex-direction: column;
    bottom: 0;
}
```

Here's a shot of Chrome dev tools to provide a bit more info.
<img width="1252" alt="screen shot 2017-03-09 at 12 31 17 pm" src="https://cloud.githubusercontent.com/assets/1398057/23748578/7b8e6b7e-04c4-11e7-8881-0e89a49b5c0f.png">

As an aside... It would be really if the CSS classes had more meaningful names. Since I'm using create-react-app and react-toolbox-themr I'm not sure at which point they're getting mangled.
