### ISSUE TITLE
Can't completely style button in snackbar without !important

### ISSUE THREAD

**Issue by flaurida** [react-toolbox/react-toolbox#1488]
Hi React Toolbox,

I am trying to style the button in the snackbar - specifically, to make the text color white and remove the fixed height. I am able to pass styles through the theme property (I changed the background to pink to be sure), but the font color and height of the button get overwritten unless I flag them as important. Please help?

Thanks,
Laura

```css
.button {
    margin: 0;
    padding: 0;
    color: #fff !important;
    font-family: 'Open Sans';
    line-height: 20px !important;
    height: auto !important;
    font-weight: 600;
    font-size: 14pt;
    background-color: pink; 
}
```

```jsx
        <MaterialSnackbar
          label={message}
          action={actionLabel}
          onClick={handleClick}
          active={true}
          type='accept'
          timeout={1000}
          theme={{ snackbar: styles.snackbar, label: styles.label, button: styles.button }}
        />
```
