### ISSUE TITLE
Firefox adds red border to required input

### ISSUE THREAD

**Issue by olegstepura** [react-toolbox/react-toolbox#1639]
Which looks like this:

![2017-08-09 16_36_54-react toolbox - spec](https://user-images.githubusercontent.com/534510/29127325-0d94edca-7d21-11e7-829c-29ff94d279c4.png)

Should be easy to fix with
```css
input:required {
    box-shadow: none;
}
```
https://stackoverflow.com/questions/3809146/firefox-4-required-input-form-red-border-outline
