### ISSUE TITLE
CardMedia horizontally aligned with CardText

### ISSUE THREAD

**Issue by busla** [react-toolbox/react-toolbox#1668]
N00b here 😄 

I´m trying to theme a Card so that CardMedia can be aligned to the left/right with CardText (as demonstrated here:

![components_cards9](https://user-images.githubusercontent.com/3162968/29997967-a5b02bb4-900f-11e7-820e-a8cad6453b7f.png)

https://material.io/guidelines/components/cards.html#cards-usage

Is my understanding correct that I create a new CardMedia and CardText theme, overriding this for example?

```css
.cardMedia {
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
  position: relative;

  &.wide,
  &.square {
    width: 100%;

    & .content {
      height: 100%;
      position: absolute;
    }

    & .content > iframe,
    & .content > video,
    & .content > img {
      max-width: 100%;
    }
  }

  &::after {
    content: '';
    display: block;
    height: 0;
  }

  &.wide::after {
    padding-top: 56.25%;
  }

  &.square::after {
    padding-top: 100%;
  }

  & .content {
    display: flex;
    flex-direction: column;
    justify-content: flex-end;
    left: 0;
    overflow: hidden;
    position: relative;
    top: 0;
    width: 100%;
  }

  & .contentOverlay {
    & .cardTitle,
    & .cardActions,
    & .cardText {
      background-color: var(--card-text-overlay);
    }
  }

  & .cardTitle {
    & .title,
    & .subtitle {
      color: var(--card-color-white);
    }
  }
}
```

Thanks for contributing!
