### ISSUE TITLE
Dialog that expands width to fit content?

### ISSUE THREAD

**Issue by joshanderson99** [react-toolbox/react-toolbox#1775]
Hi,
Is it possible to get a Dialog of "normal" type to expand it's width to fit content?  ("large" type is too wide).

Ideally there'd be a Modal component, but maybe in react-toolbox it's possible to fashion Dialog to behave similarly.

Thanks

Josh

**Comment by paulociecomp** [comment]
you can make this with css:

``` css
div[data-react-toolbox=dialog]{
  width: 900px
}
```
