### ISSUE TITLE
Theming feature appears to be broken

### ISSUE THREAD

**Issue by rokoroku** [react-toolbox/react-toolbox#1913]
According to README.md file, theming feature can be achieved by `importFrom` feature from `postcss-custom-properties` module.

However, custom variables defined in `importFrom` does not take precedence above bundled css anymore (maybe since `postcss-custom-properties@8`) 
Take a look at: https://github.com/postcss/postcss-custom-properties/issues/148

So I'd suggest using `postcss-env-function` with `postcss-custom-variable` 
e.g.)
```css
:root {
  --primary-color: env(primary-color, var(--palette-indigo-500))
}
```

References:

https://developer.mozilla.org/en-US/docs/Web/CSS/env
https://github.com/postcss/postcss-custom-properties
https://github.com/jonathantneal/postcss-env-function
