### ISSUE TITLE
How to use theme-prop on <Autocomplete /> to style <Input />

### ISSUE THREAD

**Issue by jsfr** [react-toolbox/react-toolbox#549]
Assuming I just want to change the styling of a single Autocomplete-field how do I go about changing the styling? I have tried passing in a CSS-modules `.scss` file as in the examples to the theme-prop of autocomplete with the following styles:

``` scss
.input {
  .inputElemen {
    font-size: 1em;
  }
}
```

However nothing seems to happen.
