### ISSUE TITLE
NavDrawer hidden by fixed AppBar

### ISSUE THREAD

**Issue by giacomorebonato** [react-toolbox/react-toolbox#653]
My fixed AppBar is hiding the top part of my NavDrawer.
Although there are many work around, I would like to discuss the better approach to add a top padding to my NavDrawer.
Should the prop 'style' be available on the NavDrawer?
I have access to the className prop, but I have to pass through CSS modules for not creating a global CSS class.

What would you do?

**Comment by javivelasco** [comment]
I think the best would be to create a custom theme. From your stylesheet you can import the `app_bar/_config.scss` to get access to the height variable. Then you can write a custom theme for your `Drawer` like:

```scss
// drawer-theme.css
@import '~react-toolbox/lib/app_bar/config.scss';

.drawer { // To boost priority you can add a custom className
  top: $appbar-height;
}
```

Then in your component:

```jsx
import Drawer from 'react-toolbox/lib/drawer';
import theme from './drawer-theme.scss';

// ....
  <Drawer theme={theme} ...yourprops />
// ....
```

That should work for just any component. It's an easy way to override anything. The only caveat can happen with some components with very specific selectors because of the priority, but still its perfectly possible. Hope it helps, reopen if it doesn't work!
