### ISSUE TITLE
theme style for Checkbox size

### ISSUE THREAD

**Issue by neekey** [react-toolbox/react-toolbox#782]
Hi, I want to change the size for Checkbox, and I found the theme variable is `$checkbox-size`, but according to the source code, `$checkbox-size` only change the size of the box, not will not influent the "checked check mark."

The check mark's width and height are hard coded with `$unit`. Which leads to something like below:

![image](https://cloud.githubusercontent.com/assets/499870/18373798/a5dcfc06-768a-11e6-845e-e19c842e11a3.png)

I have customized the size for the box, but the check mark is still the same.

**Comment by javivelasco** [comment]
I see. Right now the size of the checkbox mark is defined by the animation. See [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/checkbox/theme.scss#L117). Also, the animation is set in the css right [here](https://github.com/react-toolbox/react-toolbox/blob/dev/components/checkbox/theme.scss#L86). What you can do to customize it is to provide a theme as usual overriding the animation:

```scss
.smallCheckbox {
  & .check.checked:after {
    animation: custom-checkmark-expand 140ms ease-out forwards;
  }
}

@keyframes custom-checkmark-expand {
  0% {
    top: .9 * $unit;
    left: .6 * $unit;
    width: 0;
    height: 0;
  }

  100% {
    top: -.1 * $unit;
    left: .4 * $unit;
    width: .7 * $unit;      // Your custom
    height: 1.2 * $unit;   // Your custom
  }
```

You will probably need to change the positioning as well but it's more or less the same fancy. A PR is welcome to adjust those values using variables or even changing the animation with keyframes to a transition which is more correct in my opinion.

Closing since it works. Please reopen if you find any issues and sorry for the delayed response!
