### ISSUE TITLE
Slider knob prosition not updated on component resized

### ISSUE THREAD

**Issue by EmrysMyrddin** [react-toolbox/react-toolbox#794]
When using a slider in a div with dynamic size, the knob position is not updated on resize.

![capture](https://cloud.githubusercontent.com/assets/3855602/18507587/e3585076-7a68-11e6-9317-4f250a0d3d76.gif)

**Comment by EmrysMyrddin** [comment]
For more precision, here are the relevant part of the code I'm using.

##JS##

``` jsx
// Render method of my form
<div className={styles.formContainer} >
	<form onSubmit={handleSubmit} style={{}} className={styles.form}>
		<SwitchField label='Dispaly power' name='on' className={styles.input}/>
		<SliderField label='Brightness' name='lightLevel' className={styles.input}/>
		<PriceSelectorList />
	</form>
</div>
```
Here, the `PriceSelectorList` component have a variable size (based on the number of digit displayed). So when the digit number change, the Slider is not well updated. A windows size change or a click on the Slider update it as expected.

```jsx
//SliderField code

const renderSlider = ({input: {value, ...input}, meta, label, ...props}) => (
	<Row>
		<Col xs={3}><span className={styles.label}>
			{label}
		</span></Col>
		<Col xs={9}>
			<Slider step={1} pinned editable {...input} {...props}/>
		</Col>
	</Row>
)

const SliderField = props => (
	<Field {...props} type='number' component={renderSlider} initialValue={50}/>
)
```

##CSS##

```css
/* form.css */
.input {
	margin-bottom: 20px;
	text-align: left;
}

.form {
	display: flex;
	flex-flow: column;
	flex: 0 1 0;
}

.formContainer {
	display: flex;
	justify-content: center;
}
```

```css
/* SliderField.css */
.label {
	display: inline-block;
    max-width: 100%;
    padding-top: 9px;
    font-weight: 700;
}
```
