### ISSUE TITLE
Input radio responsive

### ISSUE THREAD

**Issue by euharrison** [react-toolbox/react-toolbox#807]
Hi!

Did you consider remove `white-space: nowrap` from radio input?

Something like this should enable multiline radio buttons, what is excellent for mobile version with long text:

file: `/lib/radio/theme.scss`

``` scss
.field {
  height: auto;
}

.text {
  white-space: initial;
}
```

Actual: 
![screen shot 2016-09-20 at 11 46 27](https://cloud.githubusercontent.com/assets/557598/18675163/e405fd5c-7f27-11e6-809e-c74716db088d.png)

Fixed:
![screen shot 2016-09-20 at 11 47 59](https://cloud.githubusercontent.com/assets/557598/18675235/21c7c058-7f28-11e6-8811-fba02d9ab2f5.png)
