### ISSUE TITLE
Tooltips have wrong positioning in dialogs

### ISSUE THREAD

**Issue by adamscybot** [react-toolbox/react-toolbox#94]
The Tooltip component relies on ```position: fixed```. This works in most cases, unless you want to use tooltips within dialogs. In this case, the tooltip is massively offset as it is relative to the dialog and not the window.

**Comment by javivelasco** [comment]
Ok, thanks for reporting! Working on it for the next release cc @soyjavi

**Comment by adamscybot** [comment]
For anyone who needs this urgently, heres a temporary (horrible) hack :)

```css
.your-tooltip[style] {
    top: 0 !important;
    left: 0 !important;
}

```
